runtime: php55
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /(.+\.php)$
  script: \1

- url: /
  script: index.php

- url: /second
  script: second.php
